// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: medusa/v1/cluster.proto

package medusav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Member is a single node in the cluster.
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // stable, unique node id
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // host:port the node's transport listens on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_medusa_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_medusa_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// JoinRequest is sent by a joining node to a seed node.
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     *Member                `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_medusa_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetCandidate() *Member {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// JoinResponse returns the seed's full membership view.
type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_medusa_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_medusa_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// Heartbeat is sent periodically to assert liveness.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_medusa_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_medusa_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// MemberList is the gossiped membership view. version is a monotonically
// increasing epoch so receivers can ignore stale views.
type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_medusa_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_medusa_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *MemberList) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberList) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// LeaveRequest announces that a member is departing gracefully, so peers remove
// it and rebalance immediately instead of waiting for failure detection.
type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_medusa_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

var File_medusa_v1_cluster_proto protoreflect.FileDescriptor

const file_medusa_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x17medusa/v1/cluster.proto\x12\tmedusa.v1\",\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\">\n" +
	"\vJoinRequest\x12/\n" +
	"\tcandidate\x18\x01 \x01(\v2\x11.medusa.v1.MemberR\tcandidate\";\n" +
	"\fJoinResponse\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.medusa.v1.MemberR\amembers\"D\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"S\n" +
	"\n" +
	"MemberList\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.medusa.v1.MemberR\amembers\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"+\n" +
	"\fLeaveRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberIdB\x9c\x01\n" +
	"\rcom.medusa.v1B\fClusterProtoP\x01Z8github.com/lodgvideon/medusa/genproto/medusa/v1;medusav1\xa2\x02\x03MXX\xaa\x02\tMedusa.V1\xca\x02\tMedusa\\V1\xe2\x02\x15Medusa\\V1\\GPBMetadata\xea\x02\n" +
	"Medusa::V1b\x06proto3"

var (
	file_medusa_v1_cluster_proto_rawDescOnce sync.Once
	file_medusa_v1_cluster_proto_rawDescData []byte
)

func file_medusa_v1_cluster_proto_rawDescGZIP() []byte {
	file_medusa_v1_cluster_proto_rawDescOnce.Do(func() {
		file_medusa_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medusa_v1_cluster_proto_rawDesc), len(file_medusa_v1_cluster_proto_rawDesc)))
	})
	return file_medusa_v1_cluster_proto_rawDescData
}

var file_medusa_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_medusa_v1_cluster_proto_goTypes = []any{
	(*Member)(nil),       // 0: medusa.v1.Member
	(*JoinRequest)(nil),  // 1: medusa.v1.JoinRequest
	(*JoinResponse)(nil), // 2: medusa.v1.JoinResponse
	(*Heartbeat)(nil),    // 3: medusa.v1.Heartbeat
	(*MemberList)(nil),   // 4: medusa.v1.MemberList
	(*LeaveRequest)(nil), // 5: medusa.v1.LeaveRequest
}
var file_medusa_v1_cluster_proto_depIdxs = []int32{
	0, // 0: medusa.v1.JoinRequest.candidate:type_name -> medusa.v1.Member
	0, // 1: medusa.v1.JoinResponse.members:type_name -> medusa.v1.Member
	0, // 2: medusa.v1.MemberList.members:type_name -> medusa.v1.Member
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_medusa_v1_cluster_proto_init() }
func file_medusa_v1_cluster_proto_init() {
	if File_medusa_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medusa_v1_cluster_proto_rawDesc), len(file_medusa_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_medusa_v1_cluster_proto_goTypes,
		DependencyIndexes: file_medusa_v1_cluster_proto_depIdxs,
		MessageInfos:      file_medusa_v1_cluster_proto_msgTypes,
	}.Build()
	File_medusa_v1_cluster_proto = out.File
	file_medusa_v1_cluster_proto_goTypes = nil
	file_medusa_v1_cluster_proto_depIdxs = nil
}
