// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: medusa/v1/map.proto

package medusav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PutRequest writes a key/value into a named map. When backup is true the
// request targets a backup owner and must not be re-replicated.
type PutRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Map    string                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Key    []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Backup bool                   `protobuf:"varint,4,opt,name=backup,proto3" json:"backup,omitempty"`
	// ttl_ms is the time-to-live in milliseconds; 0 means the entry never
	// expires. On replication and migration it carries the remaining lifetime.
	TtlMs         int64 `protobuf:"varint,5,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_medusa_v1_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

func (x *PutRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"` // true if the key was newly inserted (not an overwrite)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_medusa_v1_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           string                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_medusa_v1_map_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_medusa_v1_map_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           string                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Backup        bool                   `protobuf:"varint,3,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_medusa_v1_map_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *RemoveRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RemoveRequest) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existed       bool                   `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_medusa_v1_map_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

// ExecuteRequest runs a named server-side processor against a key, atomically,
// on the partition owner.
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           string                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Processor     string                 `protobuf:"bytes,3,opt,name=processor,proto3" json:"processor,omitempty"` // registered processor name (e.g. "incr")
	Arg           []byte                 `protobuf:"bytes,4,opt,name=arg,proto3" json:"arg,omitempty"`             // processor-specific argument
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_medusa_v1_map_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *ExecuteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ExecuteRequest) GetProcessor() string {
	if x != nil {
		return x.Processor
	}
	return ""
}

func (x *ExecuteRequest) GetArg() []byte {
	if x != nil {
		return x.Arg
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_medusa_v1_map_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// SnapshotEntry is one persisted key/value with its absolute expiry.
type SnapshotEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           string                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"` // unix nanoseconds, 0 = never
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEntry) Reset() {
	*x = SnapshotEntry{}
	mi := &file_medusa_v1_map_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEntry) ProtoMessage() {}

func (x *SnapshotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEntry.ProtoReflect.Descriptor instead.
func (*SnapshotEntry) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotEntry) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *SnapshotEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SnapshotEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SnapshotEntry) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// Snapshot is a node's full on-disk state, written periodically and reloaded on
// restart so the cluster survives a whole-cluster outage.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SnapshotEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_medusa_v1_map_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{9}
}

func (x *Snapshot) GetEntries() []*SnapshotEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// DigestRequest carries an owner's content digest for a partition so a backup
// can decide, without transferring data, whether it is already in sync. Used by
// active anti-entropy to skip re-pushing partitions whose replica already
// matches.
type DigestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Digest        uint64                 `protobuf:"varint,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestRequest) Reset() {
	*x = DigestRequest{}
	mi := &file_medusa_v1_map_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestRequest) ProtoMessage() {}

func (x *DigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestRequest.ProtoReflect.Descriptor instead.
func (*DigestRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{10}
}

func (x *DigestRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *DigestRequest) GetDigest() uint64 {
	if x != nil {
		return x.Digest
	}
	return 0
}

type DigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         bool                   `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"` // true if the backup's digest for the partition equals the owner's
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestResponse) Reset() {
	*x = DigestResponse{}
	mi := &file_medusa_v1_map_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestResponse) ProtoMessage() {}

func (x *DigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestResponse.ProtoReflect.Descriptor instead.
func (*DigestResponse) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{11}
}

func (x *DigestResponse) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

// SizeRequest asks a peer how many live entries it OWNS for a named map (entries
// in partitions it is the owner of, so a cluster-wide sum counts each entry once
// and never double-counts a backup copy).
type SizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           string                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeRequest) Reset() {
	*x = SizeRequest{}
	mi := &file_medusa_v1_map_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeRequest) ProtoMessage() {}

func (x *SizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeRequest.ProtoReflect.Descriptor instead.
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{12}
}

func (x *SizeRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

type SizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeResponse) Reset() {
	*x = SizeResponse{}
	mi := &file_medusa_v1_map_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeResponse) ProtoMessage() {}

func (x *SizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_map_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeResponse.ProtoReflect.Descriptor instead.
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return file_medusa_v1_map_proto_rawDescGZIP(), []int{13}
}

func (x *SizeResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_medusa_v1_map_proto protoreflect.FileDescriptor

const file_medusa_v1_map_proto_rawDesc = "" +
	"\n" +
	"\x13medusa/v1/map.proto\x12\tmedusa.v1\"u\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03map\x18\x01 \x01(\tR\x03map\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x16\n" +
	"\x06backup\x18\x04 \x01(\bR\x06backup\x12\x15\n" +
	"\x06ttl_ms\x18\x05 \x01(\x03R\x05ttlMs\"'\n" +
	"\vPutResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\"0\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03map\x18\x01 \x01(\tR\x03map\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"K\n" +
	"\rRemoveRequest\x12\x10\n" +
	"\x03map\x18\x01 \x01(\tR\x03map\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x16\n" +
	"\x06backup\x18\x03 \x01(\bR\x06backup\"*\n" +
	"\x0eRemoveResponse\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\"d\n" +
	"\x0eExecuteRequest\x12\x10\n" +
	"\x03map\x18\x01 \x01(\tR\x03map\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1c\n" +
	"\tprocessor\x18\x03 \x01(\tR\tprocessor\x12\x10\n" +
	"\x03arg\x18\x04 \x01(\fR\x03arg\")\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"f\n" +
	"\rSnapshotEntry\x12\x10\n" +
	"\x03map\x18\x01 \x01(\tR\x03map\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\">\n" +
	"\bSnapshot\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.medusa.v1.SnapshotEntryR\aentries\"E\n" +
	"\rDigestRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\x04R\x06digest\"&\n" +
	"\x0eDigestResponse\x12\x14\n" +
	"\x05match\x18\x01 \x01(\bR\x05match\"\x1f\n" +
	"\vSizeRequest\x12\x10\n" +
	"\x03map\x18\x01 \x01(\tR\x03map\"$\n" +
	"\fSizeResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05countB\x98\x01\n" +
	"\rcom.medusa.v1B\bMapProtoP\x01Z8github.com/lodgvideon/medusa/genproto/medusa/v1;medusav1\xa2\x02\x03MXX\xaa\x02\tMedusa.V1\xca\x02\tMedusa\\V1\xe2\x02\x15Medusa\\V1\\GPBMetadata\xea\x02\n" +
	"Medusa::V1b\x06proto3"

var (
	file_medusa_v1_map_proto_rawDescOnce sync.Once
	file_medusa_v1_map_proto_rawDescData []byte
)

func file_medusa_v1_map_proto_rawDescGZIP() []byte {
	file_medusa_v1_map_proto_rawDescOnce.Do(func() {
		file_medusa_v1_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medusa_v1_map_proto_rawDesc), len(file_medusa_v1_map_proto_rawDesc)))
	})
	return file_medusa_v1_map_proto_rawDescData
}

var file_medusa_v1_map_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_medusa_v1_map_proto_goTypes = []any{
	(*PutRequest)(nil),      // 0: medusa.v1.PutRequest
	(*PutResponse)(nil),     // 1: medusa.v1.PutResponse
	(*GetRequest)(nil),      // 2: medusa.v1.GetRequest
	(*GetResponse)(nil),     // 3: medusa.v1.GetResponse
	(*RemoveRequest)(nil),   // 4: medusa.v1.RemoveRequest
	(*RemoveResponse)(nil),  // 5: medusa.v1.RemoveResponse
	(*ExecuteRequest)(nil),  // 6: medusa.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 7: medusa.v1.ExecuteResponse
	(*SnapshotEntry)(nil),   // 8: medusa.v1.SnapshotEntry
	(*Snapshot)(nil),        // 9: medusa.v1.Snapshot
	(*DigestRequest)(nil),   // 10: medusa.v1.DigestRequest
	(*DigestResponse)(nil),  // 11: medusa.v1.DigestResponse
	(*SizeRequest)(nil),     // 12: medusa.v1.SizeRequest
	(*SizeResponse)(nil),    // 13: medusa.v1.SizeResponse
}
var file_medusa_v1_map_proto_depIdxs = []int32{
	8, // 0: medusa.v1.Snapshot.entries:type_name -> medusa.v1.SnapshotEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_medusa_v1_map_proto_init() }
func file_medusa_v1_map_proto_init() {
	if File_medusa_v1_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medusa_v1_map_proto_rawDesc), len(file_medusa_v1_map_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_medusa_v1_map_proto_goTypes,
		DependencyIndexes: file_medusa_v1_map_proto_depIdxs,
		MessageInfos:      file_medusa_v1_map_proto_msgTypes,
	}.Build()
	File_medusa_v1_map_proto = out.File
	file_medusa_v1_map_proto_goTypes = nil
	file_medusa_v1_map_proto_depIdxs = nil
}
