// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: medusa/v1/transport.proto

package medusav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType discriminates the payload carried in a transport frame.
// The frame header carries this as a single byte, so the receiver knows
// which concrete message to UnmarshalVT without a wrapping oneof — which
// would cost an extra heap allocation on every RPC.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED        MessageType = 0
	MessageType_MESSAGE_TYPE_ERROR              MessageType = 1
	MessageType_MESSAGE_TYPE_JOIN_REQUEST       MessageType = 2
	MessageType_MESSAGE_TYPE_JOIN_RESPONSE      MessageType = 3
	MessageType_MESSAGE_TYPE_HEARTBEAT          MessageType = 4
	MessageType_MESSAGE_TYPE_MEMBER_LIST        MessageType = 5
	MessageType_MESSAGE_TYPE_PUT_REQUEST        MessageType = 6
	MessageType_MESSAGE_TYPE_PUT_RESPONSE       MessageType = 7
	MessageType_MESSAGE_TYPE_GET_REQUEST        MessageType = 8
	MessageType_MESSAGE_TYPE_GET_RESPONSE       MessageType = 9
	MessageType_MESSAGE_TYPE_REMOVE_REQUEST     MessageType = 10
	MessageType_MESSAGE_TYPE_REMOVE_RESPONSE    MessageType = 11
	MessageType_MESSAGE_TYPE_LEAVE              MessageType = 12
	MessageType_MESSAGE_TYPE_EXECUTE_REQUEST    MessageType = 13
	MessageType_MESSAGE_TYPE_EXECUTE_RESPONSE   MessageType = 14
	MessageType_MESSAGE_TYPE_DIGEST_REQUEST     MessageType = 15
	MessageType_MESSAGE_TYPE_DIGEST_RESPONSE    MessageType = 16
	MessageType_MESSAGE_TYPE_SIZE_REQUEST       MessageType = 17
	MessageType_MESSAGE_TYPE_SIZE_RESPONSE      MessageType = 18
	MessageType_MESSAGE_TYPE_CLEAR_REQUEST      MessageType = 19
	MessageType_MESSAGE_TYPE_CLEAR_RESPONSE     MessageType = 20
	MessageType_MESSAGE_TYPE_AGGREGATE_REQUEST  MessageType = 21
	MessageType_MESSAGE_TYPE_AGGREGATE_RESPONSE MessageType = 22
	MessageType_MESSAGE_TYPE_EVICT_REQUEST      MessageType = 23
	MessageType_MESSAGE_TYPE_EVICT_RESPONSE     MessageType = 24
	MessageType_MESSAGE_TYPE_RECONCILE_REQUEST  MessageType = 25
	MessageType_MESSAGE_TYPE_RECONCILE_RESPONSE MessageType = 26
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_ERROR",
		2:  "MESSAGE_TYPE_JOIN_REQUEST",
		3:  "MESSAGE_TYPE_JOIN_RESPONSE",
		4:  "MESSAGE_TYPE_HEARTBEAT",
		5:  "MESSAGE_TYPE_MEMBER_LIST",
		6:  "MESSAGE_TYPE_PUT_REQUEST",
		7:  "MESSAGE_TYPE_PUT_RESPONSE",
		8:  "MESSAGE_TYPE_GET_REQUEST",
		9:  "MESSAGE_TYPE_GET_RESPONSE",
		10: "MESSAGE_TYPE_REMOVE_REQUEST",
		11: "MESSAGE_TYPE_REMOVE_RESPONSE",
		12: "MESSAGE_TYPE_LEAVE",
		13: "MESSAGE_TYPE_EXECUTE_REQUEST",
		14: "MESSAGE_TYPE_EXECUTE_RESPONSE",
		15: "MESSAGE_TYPE_DIGEST_REQUEST",
		16: "MESSAGE_TYPE_DIGEST_RESPONSE",
		17: "MESSAGE_TYPE_SIZE_REQUEST",
		18: "MESSAGE_TYPE_SIZE_RESPONSE",
		19: "MESSAGE_TYPE_CLEAR_REQUEST",
		20: "MESSAGE_TYPE_CLEAR_RESPONSE",
		21: "MESSAGE_TYPE_AGGREGATE_REQUEST",
		22: "MESSAGE_TYPE_AGGREGATE_RESPONSE",
		23: "MESSAGE_TYPE_EVICT_REQUEST",
		24: "MESSAGE_TYPE_EVICT_RESPONSE",
		25: "MESSAGE_TYPE_RECONCILE_REQUEST",
		26: "MESSAGE_TYPE_RECONCILE_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":        0,
		"MESSAGE_TYPE_ERROR":              1,
		"MESSAGE_TYPE_JOIN_REQUEST":       2,
		"MESSAGE_TYPE_JOIN_RESPONSE":      3,
		"MESSAGE_TYPE_HEARTBEAT":          4,
		"MESSAGE_TYPE_MEMBER_LIST":        5,
		"MESSAGE_TYPE_PUT_REQUEST":        6,
		"MESSAGE_TYPE_PUT_RESPONSE":       7,
		"MESSAGE_TYPE_GET_REQUEST":        8,
		"MESSAGE_TYPE_GET_RESPONSE":       9,
		"MESSAGE_TYPE_REMOVE_REQUEST":     10,
		"MESSAGE_TYPE_REMOVE_RESPONSE":    11,
		"MESSAGE_TYPE_LEAVE":              12,
		"MESSAGE_TYPE_EXECUTE_REQUEST":    13,
		"MESSAGE_TYPE_EXECUTE_RESPONSE":   14,
		"MESSAGE_TYPE_DIGEST_REQUEST":     15,
		"MESSAGE_TYPE_DIGEST_RESPONSE":    16,
		"MESSAGE_TYPE_SIZE_REQUEST":       17,
		"MESSAGE_TYPE_SIZE_RESPONSE":      18,
		"MESSAGE_TYPE_CLEAR_REQUEST":      19,
		"MESSAGE_TYPE_CLEAR_RESPONSE":     20,
		"MESSAGE_TYPE_AGGREGATE_REQUEST":  21,
		"MESSAGE_TYPE_AGGREGATE_RESPONSE": 22,
		"MESSAGE_TYPE_EVICT_REQUEST":      23,
		"MESSAGE_TYPE_EVICT_RESPONSE":     24,
		"MESSAGE_TYPE_RECONCILE_REQUEST":  25,
		"MESSAGE_TYPE_RECONCILE_RESPONSE": 26,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_medusa_v1_transport_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_medusa_v1_transport_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_medusa_v1_transport_proto_rawDescGZIP(), []int{0}
}

// Error is returned in place of a response payload when an RPC fails.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_medusa_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_medusa_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_medusa_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_medusa_v1_transport_proto protoreflect.FileDescriptor

const file_medusa_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x19medusa/v1/transport.proto\x12\tmedusa.v1\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xec\x06\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\x01\x12\x1d\n" +
	"\x19MESSAGE_TYPE_JOIN_REQUEST\x10\x02\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_JOIN_RESPONSE\x10\x03\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\x04\x12\x1c\n" +
	"\x18MESSAGE_TYPE_MEMBER_LIST\x10\x05\x12\x1c\n" +
	"\x18MESSAGE_TYPE_PUT_REQUEST\x10\x06\x12\x1d\n" +
	"\x19MESSAGE_TYPE_PUT_RESPONSE\x10\a\x12\x1c\n" +
	"\x18MESSAGE_TYPE_GET_REQUEST\x10\b\x12\x1d\n" +
	"\x19MESSAGE_TYPE_GET_RESPONSE\x10\t\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_REMOVE_REQUEST\x10\n" +
	"\x12 \n" +
	"\x1cMESSAGE_TYPE_REMOVE_RESPONSE\x10\v\x12\x16\n" +
	"\x12MESSAGE_TYPE_LEAVE\x10\f\x12 \n" +
	"\x1cMESSAGE_TYPE_EXECUTE_REQUEST\x10\r\x12!\n" +
	"\x1dMESSAGE_TYPE_EXECUTE_RESPONSE\x10\x0e\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_DIGEST_REQUEST\x10\x0f\x12 \n" +
	"\x1cMESSAGE_TYPE_DIGEST_RESPONSE\x10\x10\x12\x1d\n" +
	"\x19MESSAGE_TYPE_SIZE_REQUEST\x10\x11\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_SIZE_RESPONSE\x10\x12\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_CLEAR_REQUEST\x10\x13\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_CLEAR_RESPONSE\x10\x14\x12\"\n" +
	"\x1eMESSAGE_TYPE_AGGREGATE_REQUEST\x10\x15\x12#\n" +
	"\x1fMESSAGE_TYPE_AGGREGATE_RESPONSE\x10\x16\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_EVICT_REQUEST\x10\x17\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_EVICT_RESPONSE\x10\x18\x12\"\n" +
	"\x1eMESSAGE_TYPE_RECONCILE_REQUEST\x10\x19\x12#\n" +
	"\x1fMESSAGE_TYPE_RECONCILE_RESPONSE\x10\x1aB\x9e\x01\n" +
	"\rcom.medusa.v1B\x0eTransportProtoP\x01Z8github.com/lodgvideon/medusa/genproto/medusa/v1;medusav1\xa2\x02\x03MXX\xaa\x02\tMedusa.V1\xca\x02\tMedusa\\V1\xe2\x02\x15Medusa\\V1\\GPBMetadata\xea\x02\n" +
	"Medusa::V1b\x06proto3"

var (
	file_medusa_v1_transport_proto_rawDescOnce sync.Once
	file_medusa_v1_transport_proto_rawDescData []byte
)

func file_medusa_v1_transport_proto_rawDescGZIP() []byte {
	file_medusa_v1_transport_proto_rawDescOnce.Do(func() {
		file_medusa_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medusa_v1_transport_proto_rawDesc), len(file_medusa_v1_transport_proto_rawDesc)))
	})
	return file_medusa_v1_transport_proto_rawDescData
}

var file_medusa_v1_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_medusa_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_medusa_v1_transport_proto_goTypes = []any{
	(MessageType)(0), // 0: medusa.v1.MessageType
	(*Error)(nil),    // 1: medusa.v1.Error
}
var file_medusa_v1_transport_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_medusa_v1_transport_proto_init() }
func file_medusa_v1_transport_proto_init() {
	if File_medusa_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medusa_v1_transport_proto_rawDesc), len(file_medusa_v1_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_medusa_v1_transport_proto_goTypes,
		DependencyIndexes: file_medusa_v1_transport_proto_depIdxs,
		EnumInfos:         file_medusa_v1_transport_proto_enumTypes,
		MessageInfos:      file_medusa_v1_transport_proto_msgTypes,
	}.Build()
	File_medusa_v1_transport_proto = out.File
	file_medusa_v1_transport_proto_goTypes = nil
	file_medusa_v1_transport_proto_depIdxs = nil
}
